(* Generated by ocaml-tree-sitter. *)
(*
   lua grammar

   entrypoint: chunk
*)

open! Sexplib.Conv
open Tree_sitter_run

type string_start = Token.t

type string_content = Token.t

type string_end = Token.t

type shebang = Token.t (* pattern #!.* *)

type identifier = Token.t (* pattern \$?[a-zA-Z_][a-zA-Z0-9_]* *)

type number = Token.t

type comment_end = Token.t

type comment_content = Token.t

type field_separator = [
    `COMMA of Token.t (* "," *)
  | `SEMI of Token.t (* ";" *)
]

type comment_start = Token.t

type string_ = (
    string_start (*tok*)
  * string_content (*tok*) option
  * string_end (*tok*)
)

type attribute = (Token.t (* "<" *) * identifier (*tok*) * Token.t (* ">" *))

type function_identifier = (
    identifier (*tok*)
  * (Token.t (* "." *) * identifier (*tok*)) list (* zero or more *)
  * (Token.t (* ":" *) * identifier (*tok*)) option
)

type name_list = (
    identifier (*tok*)
  * (Token.t (* "," *) * identifier (*tok*)) list (* zero or more *)
)

type parameter_list = [
    `Id_rep_COMMA_id_opt_COMMA_vararg_exp of (
        identifier (*tok*)
      * (Token.t (* "," *) * identifier (*tok*)) list (* zero or more *)
      * (Token.t (* "," *) * Token.t (* "..." *)) option
    )
  | `Vararg_exp of Token.t (* "..." *)
]

type local_variable = (identifier (*tok*) * attribute option)

type local_variable_list = (
    local_variable
  * (Token.t (* "," *) * local_variable) list (* zero or more *)
)

type argument_list = [
    `LPAR_opt_exp_list_RPAR of (
        Token.t (* "(" *)
      * expression_list option
      * Token.t (* ")" *)
    )
  | `Table of table
  | `Str of string_
]

and binary_expression = [
    `Exp_or_exp of (expression * Token.t (* "or" *) * expression)
  | `Exp_and_exp of (expression * Token.t (* "and" *) * expression)
  | `Exp_EQEQ_exp of (expression * Token.t (* "==" *) * expression)
  | `Exp_TILDEEQ_exp of (expression * Token.t (* "~=" *) * expression)
  | `Exp_LT_exp of (expression * Token.t (* "<" *) * expression)
  | `Exp_GT_exp of (expression * Token.t (* ">" *) * expression)
  | `Exp_LTEQ_exp of (expression * Token.t (* "<=" *) * expression)
  | `Exp_GTEQ_exp of (expression * Token.t (* ">=" *) * expression)
  | `Exp_BAR_exp of (expression * Token.t (* "|" *) * expression)
  | `Exp_TILDE_exp of (expression * Token.t (* "~" *) * expression)
  | `Exp_AMP_exp of (expression * Token.t (* "&" *) * expression)
  | `Exp_LTLT_exp of (expression * Token.t (* "<<" *) * expression)
  | `Exp_GTGT_exp of (expression * Token.t (* ">>" *) * expression)
  | `Exp_PLUS_exp of (expression * Token.t (* "+" *) * expression)
  | `Exp_DASH_exp of (expression * Token.t (* "-" *) * expression)
  | `Exp_STAR_exp of (expression * Token.t (* "*" *) * expression)
  | `Exp_SLASH_exp of (expression * Token.t (* "/" *) * expression)
  | `Exp_SLASHSLASH_exp of (expression * Token.t (* "//" *) * expression)
  | `Exp_PERC_exp of (expression * Token.t (* "%" *) * expression)
  | `Exp_DOTDOT_exp of (expression * Token.t (* ".." *) * expression)
  | `Exp_HAT_exp of (expression * Token.t (* "^" *) * expression)
]

and block = [
    `Ret_stmt of return_statement
  | `Rep1_stmt_opt_ret_stmt of (
        statement list (* one or more *)
      * return_statement option
    )
]

and block_ = block

and else_clause = (Token.t (* "else" *) * block_ option)

and elseif_clause = (
    Token.t (* "elseif" *)
  * expression
  * Token.t (* "then" *)
  * block_ option
)

and expression = [
    `Nil of Token.t (* "nil" *)
  | `False of Token.t (* "false" *)
  | `True of Token.t (* "true" *)
  | `Num of number (*tok*)
  | `Str of string_
  | `Vararg_exp of Token.t (* "..." *)
  | `Func_defi of (Token.t (* "function" *) * function_body)
  | `Choice_var of prefix_expression
  | `Table of table
  | `Un_exp of unary_expression
  | `Bin_exp of binary_expression
]

and expression_list = (
    expression
  * (Token.t (* "," *) * expression) list (* zero or more *)
)

and field = [
    `LBRACK_exp_RBRACK_EQ_exp of (
        Token.t (* "[" *) * expression * Token.t (* "]" *)
      * Token.t (* "=" *) * expression
    )
  | `Id_EQ_exp of (identifier (*tok*) * Token.t (* "=" *) * expression)
  | `Exp of expression
]

and field_list = (
    field
  * (field_separator * field) list (* zero or more *)
  * field_separator option
)

and function_body = (
    Token.t (* "(" *)
  * parameter_list option
  * Token.t (* ")" *)
  * block_ option
  * Token.t (* "end" *)
)

and function_call = (
    prefix_expression_
  * (Token.t (* ":" *) * identifier (*tok*)) option
  * argument_list
)

and parenthesized_expression = (
    Token.t (* "(" *) * expression * Token.t (* ")" *)
)

and prefix_expression = [
    `Var of variable
  | `Func_call of function_call
  | `Paren_exp of parenthesized_expression
]

and prefix_expression_ = [
    `Var of variable
  | `Func_call of function_call
  | `Paren_exp of parenthesized_expression
]

and return_statement = (
    Token.t (* "return" *)
  * expression_list option
  * Token.t (* ";" *) option
)

and statement = [
    `Empty_stmt of Token.t (* ";" *)
  | `Var_assign of (variable_list * Token.t (* "=" *) * value_list)
  | `Local_var_decl of (
        Token.t (* "local" *)
      * local_variable_list
      * (Token.t (* "=" *) * value_list) option
    )
  | `Func_call of function_call
  | `Label_stmt of (
        Token.t (* "::" *) * identifier (*tok*) * Token.t (* "::" *)
    )
  | `Goto_stmt of (Token.t (* "goto" *) * identifier (*tok*))
  | `Brk_stmt of Token.t (* "break" *)
  | `Do_stmt of (Token.t (* "do" *) * block_ option * Token.t (* "end" *))
  | `While_stmt of (
        Token.t (* "while" *)
      * expression
      * Token.t (* "do" *)
      * block_ option
      * Token.t (* "end" *)
    )
  | `Repeat_stmt of (
        Token.t (* "repeat" *)
      * block_ option
      * Token.t (* "until" *)
      * expression
    )
  | `If_stmt of (
        Token.t (* "if" *)
      * expression
      * Token.t (* "then" *)
      * block_ option
      * elseif_clause list (* zero or more *)
      * else_clause option
      * Token.t (* "end" *)
    )
  | `For_nume_stmt of (
        Token.t (* "for" *)
      * identifier (*tok*)
      * Token.t (* "=" *)
      * expression
      * Token.t (* "," *)
      * expression
      * (Token.t (* "," *) * expression) option
      * Token.t (* "do" *)
      * block_ option
      * Token.t (* "end" *)
    )
  | `For_gene_stmt of (
        Token.t (* "for" *)
      * name_list
      * Token.t (* "in" *)
      * value_list
      * Token.t (* "do" *)
      * block_ option
      * Token.t (* "end" *)
    )
  | `Func_defi_stmt of (
        Token.t (* "function" *) * function_identifier * function_body
    )
  | `Local_func_defi_stmt of (
        Token.t (* "local" *) * Token.t (* "function" *) * identifier (*tok*)
      * function_body
    )
]

and table = (Token.t (* "{" *) * field_list option * Token.t (* "}" *))

and unary_expression = [
    `Not_exp of (Token.t (* "not" *) * expression)
  | `HASH_exp of (Token.t (* "#" *) * expression)
  | `DASH_exp of (Token.t (* "-" *) * expression)
  | `TILDE_exp of (Token.t (* "~" *) * expression)
]

and value_list = (
    expression
  * (Token.t (* "," *) * expression) list (* zero or more *)
)

and variable = [
    `Id of identifier (*tok*)
  | `Prefix_exp__LBRACK_exp_RBRACK of (
        prefix_expression_ * Token.t (* "[" *) * expression
      * Token.t (* "]" *)
    )
  | `Prefix_exp__DOT_id of (
        prefix_expression_ * Token.t (* "." *) * identifier (*tok*)
    )
]

and variable_list = (
    variable
  * (Token.t (* "," *) * variable) list (* zero or more *)
)

type chunk = (shebang (*tok*) option * block_ option)

type nil (* inlined *) = Token.t (* "nil" *)

type empty_statement (* inlined *) = Token.t (* ";" *)

type true_ (* inlined *) = Token.t (* "true" *)

type false_ (* inlined *) = Token.t (* "false" *)

type vararg_expression (* inlined *) = Token.t (* "..." *)

type break_statement (* inlined *) = Token.t (* "break" *)

type label_statement (* inlined *) = (
    Token.t (* "::" *) * identifier (*tok*) * Token.t (* "::" *)
)

type goto_statement (* inlined *) = (
    Token.t (* "goto" *) * identifier (*tok*)
)

type comment (* inlined *) = (
    comment_start (*tok*)
  * comment_content (*tok*) option
  * comment_end (*tok*)
)

type do_statement (* inlined *) = (
    Token.t (* "do" *)
  * block_ option
  * Token.t (* "end" *)
)

type for_generic_statement (* inlined *) = (
    Token.t (* "for" *)
  * name_list
  * Token.t (* "in" *)
  * value_list
  * Token.t (* "do" *)
  * block_ option
  * Token.t (* "end" *)
)

type for_numeric_statement (* inlined *) = (
    Token.t (* "for" *)
  * identifier (*tok*)
  * Token.t (* "=" *)
  * expression
  * Token.t (* "," *)
  * expression
  * (Token.t (* "," *) * expression) option
  * Token.t (* "do" *)
  * block_ option
  * Token.t (* "end" *)
)

type function_definition (* inlined *) = (
    Token.t (* "function" *) * function_body
)

type function_definition_statement (* inlined *) = (
    Token.t (* "function" *) * function_identifier * function_body
)

type if_statement (* inlined *) = (
    Token.t (* "if" *)
  * expression
  * Token.t (* "then" *)
  * block_ option
  * elseif_clause list (* zero or more *)
  * else_clause option
  * Token.t (* "end" *)
)

type local_function_definition_statement (* inlined *) = (
    Token.t (* "local" *) * Token.t (* "function" *) * identifier (*tok*)
  * function_body
)

type local_variable_declaration (* inlined *) = (
    Token.t (* "local" *)
  * local_variable_list
  * (Token.t (* "=" *) * value_list) option
)

type repeat_statement (* inlined *) = (
    Token.t (* "repeat" *)
  * block_ option
  * Token.t (* "until" *)
  * expression
)

type variable_assignment (* inlined *) = (
    variable_list * Token.t (* "=" *) * value_list
)

type while_statement (* inlined *) = (
    Token.t (* "while" *)
  * expression
  * Token.t (* "do" *)
  * block_ option
  * Token.t (* "end" *)
)

type extra = [ `Comment of Loc.t * comment ]

type extras = extra list
