(* Generated by ocaml-tree-sitter. *)

(*
   Disable warning 42:
     "this use of Foo relies on type-directed disambiguation,
     it will not compile with OCaml 4.00 or earlier."
*)
[@@@warning "-42"]

(* Disable warnings against unused variables. *)
[@@@warning "-26-27-32"]

open Tree_sitter_bindings
open Tree_sitter_run

type mt = Run.matcher_token

external create_parser :
  unit -> Tree_sitter_API.ts_parser = "octs_create_parser_lua"

let parse_source_string ?src_file contents =
  let ts_parser = create_parser () in
  Tree_sitter_parsing.parse_source_string ?src_file ts_parser contents

let parse_source_file src_file =
  let ts_parser = create_parser () in
  Tree_sitter_parsing.parse_source_file ts_parser src_file

let extras = [
  "comment";
]

let children_regexps : (string * Run.exp option) list = [
  "nil", None;
  "string_end", None;
  "empty_statement", None;
  "string_content", None;
  "string_start", None;
  "false", None;
  "identifier", None;
  "number", None;
  "comment_end", None;
  "true", None;
  "shebang", None;
  "vararg_expression", None;
  "comment_content", None;
  "comment_start", None;
  "break_statement", None;
  "string",
  Some (
    Seq [
      Token (Name "string_start");
      Opt (
        Token (Name "string_content");
      );
      Token (Name "string_end");
    ];
  );
  "label_statement",
  Some (
    Seq [
      Token (Literal "::");
      Token (Name "identifier");
      Token (Literal "::");
    ];
  );
  "goto_statement",
  Some (
    Seq [
      Token (Literal "goto");
      Token (Name "identifier");
    ];
  );
  "attribute",
  Some (
    Seq [
      Token (Literal "<");
      Token (Name "identifier");
      Token (Literal ">");
    ];
  );
  "function_identifier",
  Some (
    Seq [
      Token (Name "identifier");
      Repeat (
        Seq [
          Token (Literal ".");
          Token (Name "identifier");
        ];
      );
      Opt (
        Seq [
          Token (Literal ":");
          Token (Name "identifier");
        ];
      );
    ];
  );
  "name_list",
  Some (
    Seq [
      Token (Name "identifier");
      Repeat (
        Seq [
          Token (Literal ",");
          Token (Name "identifier");
        ];
      );
    ];
  );
  "parameter_list",
  Some (
    Alt [|
      Seq [
        Token (Name "identifier");
        Repeat (
          Seq [
            Token (Literal ",");
            Token (Name "identifier");
          ];
        );
        Opt (
          Seq [
            Token (Literal ",");
            Token (Name "vararg_expression");
          ];
        );
      ];
      Token (Name "vararg_expression");
    |];
  );
  "comment",
  Some (
    Seq [
      Token (Name "comment_start");
      Opt (
        Token (Name "comment_content");
      );
      Token (Name "comment_end");
    ];
  );
  "local_variable",
  Some (
    Seq [
      Token (Name "identifier");
      Opt (
        Token (Name "attribute");
      );
    ];
  );
  "local_variable_list",
  Some (
    Seq [
      Token (Name "local_variable");
      Repeat (
        Seq [
          Token (Literal ",");
          Token (Name "local_variable");
        ];
      );
    ];
  );
  "argument_list",
  Some (
    Alt [|
      Seq [
        Token (Literal "(");
        Opt (
          Token (Name "expression_list");
        );
        Token (Literal ")");
      ];
      Token (Name "table");
      Token (Name "string");
    |];
  );
  "binary_expression",
  Some (
    Alt [|
      Seq [
        Token (Name "expression");
        Token (Literal "or");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "and");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "==");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "~=");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "<");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal ">");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "<=");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal ">=");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "|");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "~");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "&");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "<<");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal ">>");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "+");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "-");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "*");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "/");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "//");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "%");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "..");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "expression");
        Token (Literal "^");
        Token (Name "expression");
      ];
    |];
  );
  "block",
  Some (
    Alt [|
      Token (Name "return_statement");
      Seq [
        Repeat1 (
          Token (Name "statement");
        );
        Opt (
          Token (Name "return_statement");
        );
      ];
    |];
  );
  "block_", Some (Token (Name "block"););
  "do_statement",
  Some (
    Seq [
      Token (Literal "do");
      Opt (
        Token (Name "block_");
      );
      Token (Literal "end");
    ];
  );
  "else_clause",
  Some (
    Seq [
      Token (Literal "else");
      Opt (
        Token (Name "block_");
      );
    ];
  );
  "elseif_clause",
  Some (
    Seq [
      Token (Literal "elseif");
      Token (Name "expression");
      Token (Literal "then");
      Opt (
        Token (Name "block_");
      );
    ];
  );
  "expression",
  Some (
    Alt [|
      Token (Name "nil");
      Token (Name "false");
      Token (Name "true");
      Token (Name "number");
      Token (Name "string");
      Token (Name "vararg_expression");
      Token (Name "function_definition");
      Alt [|
        Token (Name "variable");
        Token (Name "function_call");
        Token (Name "parenthesized_expression");
      |];
      Token (Name "table");
      Token (Name "unary_expression");
      Token (Name "binary_expression");
    |];
  );
  "expression_list",
  Some (
    Seq [
      Token (Name "expression");
      Repeat (
        Seq [
          Token (Literal ",");
          Token (Name "expression");
        ];
      );
    ];
  );
  "field",
  Some (
    Alt [|
      Seq [
        Token (Literal "[");
        Token (Name "expression");
        Token (Literal "]");
        Token (Literal "=");
        Token (Name "expression");
      ];
      Seq [
        Token (Name "identifier");
        Token (Literal "=");
        Token (Name "expression");
      ];
      Token (Name "expression");
    |];
  );
  "field_list",
  Some (
    Seq [
      Token (Name "field");
      Repeat (
        Seq [
          Alt [|
            Token (Literal ",");
            Token (Literal ";");
          |];
          Token (Name "field");
        ];
      );
      Opt (
        Alt [|
          Token (Literal ",");
          Token (Literal ";");
        |];
      );
    ];
  );
  "for_generic_statement",
  Some (
    Seq [
      Token (Literal "for");
      Token (Name "name_list");
      Token (Literal "in");
      Token (Name "value_list");
      Token (Literal "do");
      Opt (
        Token (Name "block_");
      );
      Token (Literal "end");
    ];
  );
  "for_numeric_statement",
  Some (
    Seq [
      Token (Literal "for");
      Token (Name "identifier");
      Token (Literal "=");
      Token (Name "expression");
      Token (Literal ",");
      Token (Name "expression");
      Opt (
        Seq [
          Token (Literal ",");
          Token (Name "expression");
        ];
      );
      Token (Literal "do");
      Opt (
        Token (Name "block_");
      );
      Token (Literal "end");
    ];
  );
  "function_body",
  Some (
    Seq [
      Token (Literal "(");
      Opt (
        Token (Name "parameter_list");
      );
      Token (Literal ")");
      Opt (
        Token (Name "block_");
      );
      Token (Literal "end");
    ];
  );
  "function_call",
  Some (
    Seq [
      Token (Name "prefix_expression_");
      Opt (
        Seq [
          Token (Literal ":");
          Token (Name "identifier");
        ];
      );
      Token (Name "argument_list");
    ];
  );
  "function_definition",
  Some (
    Seq [
      Token (Literal "function");
      Token (Name "function_body");
    ];
  );
  "function_definition_statement",
  Some (
    Seq [
      Token (Literal "function");
      Token (Name "function_identifier");
      Token (Name "function_body");
    ];
  );
  "if_statement",
  Some (
    Seq [
      Token (Literal "if");
      Token (Name "expression");
      Token (Literal "then");
      Opt (
        Token (Name "block_");
      );
      Repeat (
        Token (Name "elseif_clause");
      );
      Opt (
        Token (Name "else_clause");
      );
      Token (Literal "end");
    ];
  );
  "local_function_definition_statement",
  Some (
    Seq [
      Token (Literal "local");
      Token (Literal "function");
      Token (Name "identifier");
      Token (Name "function_body");
    ];
  );
  "local_variable_declaration",
  Some (
    Seq [
      Token (Literal "local");
      Token (Name "local_variable_list");
      Opt (
        Seq [
          Token (Literal "=");
          Token (Name "value_list");
        ];
      );
    ];
  );
  "parenthesized_expression",
  Some (
    Seq [
      Token (Literal "(");
      Token (Name "expression");
      Token (Literal ")");
    ];
  );
  "prefix_expression_",
  Some (
    Alt [|
      Token (Name "variable");
      Token (Name "function_call");
      Token (Name "parenthesized_expression");
    |];
  );
  "repeat_statement",
  Some (
    Seq [
      Token (Literal "repeat");
      Opt (
        Token (Name "block_");
      );
      Token (Literal "until");
      Token (Name "expression");
    ];
  );
  "return_statement",
  Some (
    Seq [
      Token (Literal "return");
      Opt (
        Token (Name "expression_list");
      );
      Opt (
        Token (Name "empty_statement");
      );
    ];
  );
  "statement",
  Some (
    Alt [|
      Token (Name "empty_statement");
      Token (Name "variable_assignment");
      Token (Name "local_variable_declaration");
      Token (Name "function_call");
      Token (Name "label_statement");
      Token (Name "goto_statement");
      Token (Name "break_statement");
      Token (Name "do_statement");
      Token (Name "while_statement");
      Token (Name "repeat_statement");
      Token (Name "if_statement");
      Token (Name "for_numeric_statement");
      Token (Name "for_generic_statement");
      Token (Name "function_definition_statement");
      Token (Name "local_function_definition_statement");
    |];
  );
  "table",
  Some (
    Seq [
      Token (Literal "{");
      Opt (
        Token (Name "field_list");
      );
      Token (Literal "}");
    ];
  );
  "unary_expression",
  Some (
    Alt [|
      Seq [
        Token (Literal "not");
        Token (Name "expression");
      ];
      Seq [
        Token (Literal "#");
        Token (Name "expression");
      ];
      Seq [
        Token (Literal "-");
        Token (Name "expression");
      ];
      Seq [
        Token (Literal "~");
        Token (Name "expression");
      ];
    |];
  );
  "value_list",
  Some (
    Seq [
      Token (Name "expression");
      Repeat (
        Seq [
          Token (Literal ",");
          Token (Name "expression");
        ];
      );
    ];
  );
  "variable",
  Some (
    Alt [|
      Token (Name "identifier");
      Seq [
        Token (Name "prefix_expression_");
        Token (Literal "[");
        Token (Name "expression");
        Token (Literal "]");
      ];
      Seq [
        Token (Name "prefix_expression_");
        Token (Literal ".");
        Token (Name "identifier");
      ];
    |];
  );
  "variable_assignment",
  Some (
    Seq [
      Token (Name "variable_list");
      Token (Literal "=");
      Token (Name "value_list");
    ];
  );
  "variable_list",
  Some (
    Seq [
      Token (Name "variable");
      Repeat (
        Seq [
          Token (Literal ",");
          Token (Name "variable");
        ];
      );
    ];
  );
  "while_statement",
  Some (
    Seq [
      Token (Literal "while");
      Token (Name "expression");
      Token (Literal "do");
      Opt (
        Token (Name "block_");
      );
      Token (Literal "end");
    ];
  );
  "chunk",
  Some (
    Seq [
      Opt (
        Token (Name "shebang");
      );
      Opt (
        Token (Name "block");
      );
    ];
  );
]

let trans_nil ((kind, body) : mt) : CST.nil =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_string_end ((kind, body) : mt) : CST.string_end =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_empty_statement ((kind, body) : mt) : CST.empty_statement =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_string_content ((kind, body) : mt) : CST.string_content =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_string_start ((kind, body) : mt) : CST.string_start =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_false_ ((kind, body) : mt) : CST.false_ =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_identifier ((kind, body) : mt) : CST.identifier =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_number ((kind, body) : mt) : CST.number =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_comment_end ((kind, body) : mt) : CST.comment_end =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_true_ ((kind, body) : mt) : CST.true_ =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_shebang ((kind, body) : mt) : CST.shebang =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_vararg_expression ((kind, body) : mt) : CST.vararg_expression =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_comment_content ((kind, body) : mt) : CST.comment_content =
  match body with
  | Leaf v -> v
  | Children _ -> assert false


let trans_comment_start ((kind, body) : mt) : CST.comment_start =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_break_statement ((kind, body) : mt) : CST.break_statement =
  match body with
  | Leaf v -> v
  | Children _ -> assert false

let trans_string_ ((kind, body) : mt) : CST.string_ =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            trans_string_start (Run.matcher_token v0),
            Run.opt
              (fun v -> trans_string_content (Run.matcher_token v))
              v1
            ,
            trans_string_end (Run.matcher_token v2)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

let trans_label_statement ((kind, body) : mt) : CST.label_statement =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_identifier (Run.matcher_token v1),
            Run.trans_token (Run.matcher_token v2)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

let trans_goto_statement ((kind, body) : mt) : CST.goto_statement =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_identifier (Run.matcher_token v1)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

let trans_attribute ((kind, body) : mt) : CST.attribute =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_identifier (Run.matcher_token v1),
            Run.trans_token (Run.matcher_token v2)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

let trans_function_identifier ((kind, body) : mt) : CST.function_identifier =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            trans_identifier (Run.matcher_token v0),
            Run.repeat
              (fun v ->
                (match v with
                | Seq [v0; v1] ->
                    (
                      Run.trans_token (Run.matcher_token v0),
                      trans_identifier (Run.matcher_token v1)
                    )
                | _ -> assert false
                )
              )
              v1
            ,
            Run.opt
              (fun v ->
                (match v with
                | Seq [v0; v1] ->
                    (
                      Run.trans_token (Run.matcher_token v0),
                      trans_identifier (Run.matcher_token v1)
                    )
                | _ -> assert false
                )
              )
              v2
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

let trans_name_list ((kind, body) : mt) : CST.name_list =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1] ->
          (
            trans_identifier (Run.matcher_token v0),
            Run.repeat
              (fun v ->
                (match v with
                | Seq [v0; v1] ->
                    (
                      Run.trans_token (Run.matcher_token v0),
                      trans_identifier (Run.matcher_token v1)
                    )
                | _ -> assert false
                )
              )
              v1
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

let trans_parameter_list ((kind, body) : mt) : CST.parameter_list =
  match body with
  | Children v ->
      (match v with
      | Alt (0, v) ->
          `Id_rep_COMMA_id_opt_COMMA_vararg_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_identifier (Run.matcher_token v0),
                  Run.repeat
                    (fun v ->
                      (match v with
                      | Seq [v0; v1] ->
                          (
                            Run.trans_token (Run.matcher_token v0),
                            trans_identifier (Run.matcher_token v1)
                          )
                      | _ -> assert false
                      )
                    )
                    v1
                  ,
                  Run.opt
                    (fun v ->
                      (match v with
                      | Seq [v0; v1] ->
                          (
                            Run.trans_token (Run.matcher_token v0),
                            trans_vararg_expression (Run.matcher_token v1)
                          )
                      | _ -> assert false
                      )
                    )
                    v2
                )
            | _ -> assert false
            )
          )
      | Alt (1, v) ->
          `Vararg_exp (
            trans_vararg_expression (Run.matcher_token v)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

let trans_comment ((kind, body) : mt) : CST.comment =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            trans_comment_start (Run.matcher_token v0),
            Run.opt
              (fun v -> trans_comment_content (Run.matcher_token v))
              v1
            ,
            trans_comment_end (Run.matcher_token v2)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

let trans_local_variable ((kind, body) : mt) : CST.local_variable =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1] ->
          (
            trans_identifier (Run.matcher_token v0),
            Run.opt
              (fun v -> trans_attribute (Run.matcher_token v))
              v1
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

let trans_local_variable_list ((kind, body) : mt) : CST.local_variable_list =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1] ->
          (
            trans_local_variable (Run.matcher_token v0),
            Run.repeat
              (fun v ->
                (match v with
                | Seq [v0; v1] ->
                    (
                      Run.trans_token (Run.matcher_token v0),
                      trans_local_variable (Run.matcher_token v1)
                    )
                | _ -> assert false
                )
              )
              v1
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

let rec trans_argument_list ((kind, body) : mt) : CST.argument_list =
  match body with
  | Children v ->
      (match v with
      | Alt (0, v) ->
          `LPAR_opt_exp_list_RPAR (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  Run.trans_token (Run.matcher_token v0),
                  Run.opt
                    (fun v -> trans_expression_list (Run.matcher_token v))
                    v1
                  ,
                  Run.trans_token (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (1, v) ->
          `Table (
            trans_table (Run.matcher_token v)
          )
      | Alt (2, v) ->
          `Str (
            trans_string_ (Run.matcher_token v)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_binary_expression ((kind, body) : mt) : CST.binary_expression =
  match body with
  | Children v ->
      (match v with
      | Alt (0, v) ->
          `Exp_or_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (1, v) ->
          `Exp_and_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (2, v) ->
          `Exp_EQEQ_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (3, v) ->
          `Exp_TILDEEQ_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (4, v) ->
          `Exp_LT_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (5, v) ->
          `Exp_GT_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (6, v) ->
          `Exp_LTEQ_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (7, v) ->
          `Exp_GTEQ_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (8, v) ->
          `Exp_BAR_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (9, v) ->
          `Exp_TILDE_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (10, v) ->
          `Exp_AMP_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (11, v) ->
          `Exp_LTLT_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (12, v) ->
          `Exp_GTGT_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (13, v) ->
          `Exp_PLUS_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (14, v) ->
          `Exp_DASH_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (15, v) ->
          `Exp_STAR_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (16, v) ->
          `Exp_SLASH_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (17, v) ->
          `Exp_SLASHSLASH_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (18, v) ->
          `Exp_PERC_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (19, v) ->
          `Exp_DOTDOT_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (20, v) ->
          `Exp_HAT_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_expression (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_block ((kind, body) : mt) : CST.block =
  match body with
  | Children v ->
      (match v with
      | Alt (0, v) ->
          `Ret_stmt (
            trans_return_statement (Run.matcher_token v)
          )
      | Alt (1, v) ->
          `Rep1_stmt_opt_ret_stmt (
            (match v with
            | Seq [v0; v1] ->
                (
                  Run.repeat1
                    (fun v -> trans_statement (Run.matcher_token v))
                    v0
                  ,
                  Run.opt
                    (fun v -> trans_return_statement (Run.matcher_token v))
                    v1
                )
            | _ -> assert false
            )
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_block_ ((kind, body) : mt) : CST.block_ =
  match body with
  | Children v ->
      trans_block (Run.matcher_token v)
  | Leaf _ -> assert false

and trans_do_statement ((kind, body) : mt) : CST.do_statement =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            Run.trans_token (Run.matcher_token v0),
            Run.opt
              (fun v -> trans_block_ (Run.matcher_token v))
              v1
            ,
            Run.trans_token (Run.matcher_token v2)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_else_clause ((kind, body) : mt) : CST.else_clause =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1] ->
          (
            Run.trans_token (Run.matcher_token v0),
            Run.opt
              (fun v -> trans_block_ (Run.matcher_token v))
              v1
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_elseif_clause ((kind, body) : mt) : CST.elseif_clause =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2; v3] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_expression (Run.matcher_token v1),
            Run.trans_token (Run.matcher_token v2),
            Run.opt
              (fun v -> trans_block_ (Run.matcher_token v))
              v3
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_expression ((kind, body) : mt) : CST.expression =
  match body with
  | Children v ->
      (match v with
      | Alt (0, v) ->
          `Nil (
            trans_nil (Run.matcher_token v)
          )
      | Alt (1, v) ->
          `False (
            trans_false_ (Run.matcher_token v)
          )
      | Alt (2, v) ->
          `True (
            trans_true_ (Run.matcher_token v)
          )
      | Alt (3, v) ->
          `Num (
            trans_number (Run.matcher_token v)
          )
      | Alt (4, v) ->
          `Str (
            trans_string_ (Run.matcher_token v)
          )
      | Alt (5, v) ->
          `Vararg_exp (
            trans_vararg_expression (Run.matcher_token v)
          )
      | Alt (6, v) ->
          `Func_defi (
            trans_function_definition (Run.matcher_token v)
          )
      | Alt (7, v) ->
          `Choice_var (
            (match v with
            | Alt (0, v) ->
                `Var (
                  trans_variable (Run.matcher_token v)
                )
            | Alt (1, v) ->
                `Func_call (
                  trans_function_call (Run.matcher_token v)
                )
            | Alt (2, v) ->
                `Paren_exp (
                  trans_parenthesized_expression (Run.matcher_token v)
                )
            | _ -> assert false
            )
          )
      | Alt (8, v) ->
          `Table (
            trans_table (Run.matcher_token v)
          )
      | Alt (9, v) ->
          `Un_exp (
            trans_unary_expression (Run.matcher_token v)
          )
      | Alt (10, v) ->
          `Bin_exp (
            trans_binary_expression (Run.matcher_token v)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_expression_list ((kind, body) : mt) : CST.expression_list =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1] ->
          (
            trans_expression (Run.matcher_token v0),
            Run.repeat
              (fun v ->
                (match v with
                | Seq [v0; v1] ->
                    (
                      Run.trans_token (Run.matcher_token v0),
                      trans_expression (Run.matcher_token v1)
                    )
                | _ -> assert false
                )
              )
              v1
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_field ((kind, body) : mt) : CST.field =
  match body with
  | Children v ->
      (match v with
      | Alt (0, v) ->
          `LBRACK_exp_RBRACK_EQ_exp (
            (match v with
            | Seq [v0; v1; v2; v3; v4] ->
                (
                  Run.trans_token (Run.matcher_token v0),
                  trans_expression (Run.matcher_token v1),
                  Run.trans_token (Run.matcher_token v2),
                  Run.trans_token (Run.matcher_token v3),
                  trans_expression (Run.matcher_token v4)
                )
            | _ -> assert false
            )
          )
      | Alt (1, v) ->
          `Id_EQ_exp (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_identifier (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | Alt (2, v) ->
          `Exp (
            trans_expression (Run.matcher_token v)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_field_list ((kind, body) : mt) : CST.field_list =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            trans_field (Run.matcher_token v0),
            Run.repeat
              (fun v ->
                (match v with
                | Seq [v0; v1] ->
                    (
                      (match v0 with
                      | Alt (0, v) ->
                          `COMMA (
                            Run.trans_token (Run.matcher_token v)
                          )
                      | Alt (1, v) ->
                          `SEMI (
                            Run.trans_token (Run.matcher_token v)
                          )
                      | _ -> assert false
                      )
                      ,
                      trans_field (Run.matcher_token v1)
                    )
                | _ -> assert false
                )
              )
              v1
            ,
            Run.opt
              (fun v ->
                (match v with
                | Alt (0, v) ->
                    `COMMA (
                      Run.trans_token (Run.matcher_token v)
                    )
                | Alt (1, v) ->
                    `SEMI (
                      Run.trans_token (Run.matcher_token v)
                    )
                | _ -> assert false
                )
              )
              v2
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_for_generic_statement ((kind, body) : mt) : CST.for_generic_statement =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2; v3; v4; v5; v6] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_name_list (Run.matcher_token v1),
            Run.trans_token (Run.matcher_token v2),
            trans_value_list (Run.matcher_token v3),
            Run.trans_token (Run.matcher_token v4),
            Run.opt
              (fun v -> trans_block_ (Run.matcher_token v))
              v5
            ,
            Run.trans_token (Run.matcher_token v6)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_for_numeric_statement ((kind, body) : mt) : CST.for_numeric_statement =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2; v3; v4; v5; v6; v7; v8; v9] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_identifier (Run.matcher_token v1),
            Run.trans_token (Run.matcher_token v2),
            trans_expression (Run.matcher_token v3),
            Run.trans_token (Run.matcher_token v4),
            trans_expression (Run.matcher_token v5),
            Run.opt
              (fun v ->
                (match v with
                | Seq [v0; v1] ->
                    (
                      Run.trans_token (Run.matcher_token v0),
                      trans_expression (Run.matcher_token v1)
                    )
                | _ -> assert false
                )
              )
              v6
            ,
            Run.trans_token (Run.matcher_token v7),
            Run.opt
              (fun v -> trans_block_ (Run.matcher_token v))
              v8
            ,
            Run.trans_token (Run.matcher_token v9)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_function_body ((kind, body) : mt) : CST.function_body =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2; v3; v4] ->
          (
            Run.trans_token (Run.matcher_token v0),
            Run.opt
              (fun v -> trans_parameter_list (Run.matcher_token v))
              v1
            ,
            Run.trans_token (Run.matcher_token v2),
            Run.opt
              (fun v -> trans_block_ (Run.matcher_token v))
              v3
            ,
            Run.trans_token (Run.matcher_token v4)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_function_call ((kind, body) : mt) : CST.function_call =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            trans_prefix_expression_ (Run.matcher_token v0),
            Run.opt
              (fun v ->
                (match v with
                | Seq [v0; v1] ->
                    (
                      Run.trans_token (Run.matcher_token v0),
                      trans_identifier (Run.matcher_token v1)
                    )
                | _ -> assert false
                )
              )
              v1
            ,
            trans_argument_list (Run.matcher_token v2)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_function_definition ((kind, body) : mt) : CST.function_definition =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_function_body (Run.matcher_token v1)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_function_definition_statement ((kind, body) : mt) : CST.function_definition_statement =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_function_identifier (Run.matcher_token v1),
            trans_function_body (Run.matcher_token v2)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_if_statement ((kind, body) : mt) : CST.if_statement =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2; v3; v4; v5; v6] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_expression (Run.matcher_token v1),
            Run.trans_token (Run.matcher_token v2),
            Run.opt
              (fun v -> trans_block_ (Run.matcher_token v))
              v3
            ,
            Run.repeat
              (fun v -> trans_elseif_clause (Run.matcher_token v))
              v4
            ,
            Run.opt
              (fun v -> trans_else_clause (Run.matcher_token v))
              v5
            ,
            Run.trans_token (Run.matcher_token v6)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_local_function_definition_statement ((kind, body) : mt) : CST.local_function_definition_statement =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2; v3] ->
          (
            Run.trans_token (Run.matcher_token v0),
            Run.trans_token (Run.matcher_token v1),
            trans_identifier (Run.matcher_token v2),
            trans_function_body (Run.matcher_token v3)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_local_variable_declaration ((kind, body) : mt) : CST.local_variable_declaration =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_local_variable_list (Run.matcher_token v1),
            Run.opt
              (fun v ->
                (match v with
                | Seq [v0; v1] ->
                    (
                      Run.trans_token (Run.matcher_token v0),
                      trans_value_list (Run.matcher_token v1)
                    )
                | _ -> assert false
                )
              )
              v2
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_parenthesized_expression ((kind, body) : mt) : CST.parenthesized_expression =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_expression (Run.matcher_token v1),
            Run.trans_token (Run.matcher_token v2)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_prefix_expression_ ((kind, body) : mt) : CST.prefix_expression_ =
  match body with
  | Children v ->
      (match v with
      | Alt (0, v) ->
          `Var (
            trans_variable (Run.matcher_token v)
          )
      | Alt (1, v) ->
          `Func_call (
            trans_function_call (Run.matcher_token v)
          )
      | Alt (2, v) ->
          `Paren_exp (
            trans_parenthesized_expression (Run.matcher_token v)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_repeat_statement ((kind, body) : mt) : CST.repeat_statement =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2; v3] ->
          (
            Run.trans_token (Run.matcher_token v0),
            Run.opt
              (fun v -> trans_block_ (Run.matcher_token v))
              v1
            ,
            Run.trans_token (Run.matcher_token v2),
            trans_expression (Run.matcher_token v3)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_return_statement ((kind, body) : mt) : CST.return_statement =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            Run.trans_token (Run.matcher_token v0),
            Run.opt
              (fun v -> trans_expression_list (Run.matcher_token v))
              v1
            ,
            Run.opt
              (fun v -> trans_empty_statement (Run.matcher_token v))
              v2
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_statement ((kind, body) : mt) : CST.statement =
  match body with
  | Children v ->
      (match v with
      | Alt (0, v) ->
          `Empty_stmt (
            trans_empty_statement (Run.matcher_token v)
          )
      | Alt (1, v) ->
          `Var_assign (
            trans_variable_assignment (Run.matcher_token v)
          )
      | Alt (2, v) ->
          `Local_var_decl (
            trans_local_variable_declaration (Run.matcher_token v)
          )
      | Alt (3, v) ->
          `Func_call (
            trans_function_call (Run.matcher_token v)
          )
      | Alt (4, v) ->
          `Label_stmt (
            trans_label_statement (Run.matcher_token v)
          )
      | Alt (5, v) ->
          `Goto_stmt (
            trans_goto_statement (Run.matcher_token v)
          )
      | Alt (6, v) ->
          `Brk_stmt (
            trans_break_statement (Run.matcher_token v)
          )
      | Alt (7, v) ->
          `Do_stmt (
            trans_do_statement (Run.matcher_token v)
          )
      | Alt (8, v) ->
          `While_stmt (
            trans_while_statement (Run.matcher_token v)
          )
      | Alt (9, v) ->
          `Repeat_stmt (
            trans_repeat_statement (Run.matcher_token v)
          )
      | Alt (10, v) ->
          `If_stmt (
            trans_if_statement (Run.matcher_token v)
          )
      | Alt (11, v) ->
          `For_nume_stmt (
            trans_for_numeric_statement (Run.matcher_token v)
          )
      | Alt (12, v) ->
          `For_gene_stmt (
            trans_for_generic_statement (Run.matcher_token v)
          )
      | Alt (13, v) ->
          `Func_defi_stmt (
            trans_function_definition_statement (Run.matcher_token v)
          )
      | Alt (14, v) ->
          `Local_func_defi_stmt (
            trans_local_function_definition_statement (Run.matcher_token v)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_table ((kind, body) : mt) : CST.table =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            Run.trans_token (Run.matcher_token v0),
            Run.opt
              (fun v -> trans_field_list (Run.matcher_token v))
              v1
            ,
            Run.trans_token (Run.matcher_token v2)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_unary_expression ((kind, body) : mt) : CST.unary_expression =
  match body with
  | Children v ->
      (match v with
      | Alt (0, v) ->
          `Not_exp (
            (match v with
            | Seq [v0; v1] ->
                (
                  Run.trans_token (Run.matcher_token v0),
                  trans_expression (Run.matcher_token v1)
                )
            | _ -> assert false
            )
          )
      | Alt (1, v) ->
          `HASH_exp (
            (match v with
            | Seq [v0; v1] ->
                (
                  Run.trans_token (Run.matcher_token v0),
                  trans_expression (Run.matcher_token v1)
                )
            | _ -> assert false
            )
          )
      | Alt (2, v) ->
          `DASH_exp (
            (match v with
            | Seq [v0; v1] ->
                (
                  Run.trans_token (Run.matcher_token v0),
                  trans_expression (Run.matcher_token v1)
                )
            | _ -> assert false
            )
          )
      | Alt (3, v) ->
          `TILDE_exp (
            (match v with
            | Seq [v0; v1] ->
                (
                  Run.trans_token (Run.matcher_token v0),
                  trans_expression (Run.matcher_token v1)
                )
            | _ -> assert false
            )
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_value_list ((kind, body) : mt) : CST.value_list =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1] ->
          (
            trans_expression (Run.matcher_token v0),
            Run.repeat
              (fun v ->
                (match v with
                | Seq [v0; v1] ->
                    (
                      Run.trans_token (Run.matcher_token v0),
                      trans_expression (Run.matcher_token v1)
                    )
                | _ -> assert false
                )
              )
              v1
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_variable ((kind, body) : mt) : CST.variable =
  match body with
  | Children v ->
      (match v with
      | Alt (0, v) ->
          `Id (
            trans_identifier (Run.matcher_token v)
          )
      | Alt (1, v) ->
          `Prefix_exp__LBRACK_exp_RBRACK (
            (match v with
            | Seq [v0; v1; v2; v3] ->
                (
                  trans_prefix_expression_ (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_expression (Run.matcher_token v2),
                  Run.trans_token (Run.matcher_token v3)
                )
            | _ -> assert false
            )
          )
      | Alt (2, v) ->
          `Prefix_exp__DOT_id (
            (match v with
            | Seq [v0; v1; v2] ->
                (
                  trans_prefix_expression_ (Run.matcher_token v0),
                  Run.trans_token (Run.matcher_token v1),
                  trans_identifier (Run.matcher_token v2)
                )
            | _ -> assert false
            )
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_variable_assignment ((kind, body) : mt) : CST.variable_assignment =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2] ->
          (
            trans_variable_list (Run.matcher_token v0),
            Run.trans_token (Run.matcher_token v1),
            trans_value_list (Run.matcher_token v2)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_variable_list ((kind, body) : mt) : CST.variable_list =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1] ->
          (
            trans_variable (Run.matcher_token v0),
            Run.repeat
              (fun v ->
                (match v with
                | Seq [v0; v1] ->
                    (
                      Run.trans_token (Run.matcher_token v0),
                      trans_variable (Run.matcher_token v1)
                    )
                | _ -> assert false
                )
              )
              v1
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

and trans_while_statement ((kind, body) : mt) : CST.while_statement =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1; v2; v3; v4] ->
          (
            Run.trans_token (Run.matcher_token v0),
            trans_expression (Run.matcher_token v1),
            Run.trans_token (Run.matcher_token v2),
            Run.opt
              (fun v -> trans_block_ (Run.matcher_token v))
              v3
            ,
            Run.trans_token (Run.matcher_token v4)
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false

let trans_chunk ((kind, body) : mt) : CST.chunk =
  match body with
  | Children v ->
      (match v with
      | Seq [v0; v1] ->
          (
            Run.opt
              (fun v -> trans_shebang (Run.matcher_token v))
              v0
            ,
            Run.opt
              (fun v -> trans_block (Run.matcher_token v))
              v1
          )
      | _ -> assert false
      )
  | Leaf _ -> assert false


(*
   Costly operation that translates a whole tree or subtree.

   The first pass translates it into a generic tree structure suitable
   to guess which node corresponds to each grammar rule.
   The second pass is a translation into a typed tree where each grammar
   node has its own type.

   This function is called:
   - once on the root of the program after removing extras
     (comments and other nodes that occur anywhere independently from
     the grammar);
   - once of each extra node, resulting in its own independent tree of type
     'extra'.
*)
let translate_tree src node trans_x =
  let matched_tree = Run.match_tree children_regexps src node in
  Option.map trans_x matched_tree


let translate_extra src (node : Tree_sitter_output_t.node) : CST.extra option =
  match node.type_ with
  | "comment" ->
      (match translate_tree src node trans_comment with
      | None -> None
      | Some x -> Some (`Comment (Run.get_loc node, x)))
  | _ -> None

let translate_root src root_node =
  translate_tree src root_node trans_chunk

let parse_input_tree input_tree =
  let orig_root_node = Tree_sitter_parsing.root input_tree in
  let src = Tree_sitter_parsing.src input_tree in
  let errors = Run.extract_errors src orig_root_node in
  let opt_program, extras =
     Run.translate
       ~extras
       ~translate_root:(translate_root src)
       ~translate_extra:(translate_extra src)
       orig_root_node
  in
  Parsing_result.create src opt_program extras errors

let string ?src_file contents =
  let input_tree = parse_source_string ?src_file contents in
  parse_input_tree input_tree

let file src_file =
  let input_tree = parse_source_file src_file in
  parse_input_tree input_tree

